export const REPAIR_LIST = 'REPAIR_LIST'
export const REPAIR_PHONE = 'REPAIR_PHONE'
export const MODEL_PHONE = 'MODEL_PHONE'
export const GET_MODEL = 'GET_MODEL'
export const GET_REPAIR = 'GET_REPAIR'
export const POST_REQUEST = 'POST_REQUEST'
